### ISSUE TITLE
extend the type of options.

### ISSUE THREAD

**Issue by EdamAme-x** [fzn0x/hypf#10]
#### What feature are you want to add?
I want to extend the type of options.

Currently, adding an option with otherOptions results in a type error.
![image](https://github.com/fzn0x/hypf/assets/121654029/d8e2c81c-d7df-4c69-a745-aa93b18c0acc)

#### Why this feature is important?
It will be no longer necessary to mark it as a type error.

#### Describe the feature

`await hypfFetcher.get<dataType, {
  proxy: string
}>`

#### Checklist

- [ ] I'm willing to submit a pull request
- [x] I have read the documentation and made sure this feature doesn't already exist.

**Comment by EdamAme-x** [comment]
I forget this.
It's in Bun.

**Comment by fzn0x** [comment]
Will be added in `v0.2.2`

I will introduce how to migrate from previous versions to v0.2.2

**Comment by fzn0x** [comment]
https://github.com/fzn0x/hypf/releases/tag/v0.2.2 is released
