### ISSUE TITLE
After doing a preRequest, hypf should retrieve the property from the options.

### ISSUE THREAD

**Issue by EdamAme-x** [fzn0x/hypf#11]
#### What feature are you want to add?

The reason is that I can play with otpions within preRequest.

https://github.com/fzn0x/hypf/blob/main/src/utils/create-request.ts#L44

#### Describe the feature

This is useful for common settings.

#### Checklist

- [ ] I'm willing to submit a pull request
- [x] I have read the documentation and made sure this feature doesn't already exist.

**Comment by fzn0x** [comment]
This is a good request

Indeed, we should do more with the Hooks, I will check first and work on it

**Comment by fzn0x** [comment]
https://github.com/fzn0x/hypf/releases/tag/v0.2.2 is released
