### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Kenzomalik** [fzn0x/hypf#14]
#### Bug description

...

#### What is actually happening?

...

#### What do you expect to happen?

...

#### Code to reproduce

```js

```

#### Checklist

- [ ] I'm willing to submit a pull request
- [ ] I have read the documentation.
- [ ] I have tried my code with the latest version of npm and [hypf](https://github.com/fzn0x/hypf).

**Comment by fzn0x** [comment]
Need more details
